version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - $PORT:3000
    environment:
      - NODE_ENV=development
    command: ["yarn", "start"]
